Repository mayadata-io/gui-automation, pull requests merged in 2020-06, with the labels that each got.

#27 Bug fix
  main/pages/DashboardPage.py
  tests/auth_test.py
Labels: bug-fix

#30 Local user, Admin and performance auth test update
  main/pages/SidePanel.py
  main/pages/register/OnboardingPage.py
  pytest.ini
  tests/auth_test.py
Labels: authentication

#33 New project field xpath update
  conftest.py
  main/pages/register/OnboardingPage.py
Labels: bug-fix, enhancement

#35 Add mysql Dmaas backup restore testCase
  tests/dmaas_test.py
Labels: dmaas, mysql

#37 fix: Invite team access button attribute modify
  main/pages/UserRolesPage.py
Labels: teaming
